kuznia-rdzeni/transactron

test/testing/test_method_mock.py, transactron/testing/method_mock.py
Reopened rebased #7 
---
I accidentally found new use for @def_method_mock (?), because it worked on older Transactron in other project.
It is nice to use (and more intuitive than in testbench example use) for proving input / collecting output of input-only and output-only Methods in modules, instead of writing call loops, and can be used directly for driving SimpleTestCircuit generated TestbenchIOs.
=> Allow using AdapterBase in MethodMock

transactron/lib/storage.py
This change is meant for testbench usage, e.g. inspecting the register file during Coreblocks core tests.
=> Expose internal memory in memory banks

pyproject.toml, test/core/test_transactions.py, test/lib/test_connectors.py, test/lib/test_fifo.py, test/lib/test_metrics.py, test/lib/test_transformers.py, test/test_assign.py, test/test_connectors.py, test/test_methods.py, test/utils/test_onehotswitch.py, test/utils/test_utils.py
This PR removes the dependency on `parameterized`, `pytest.mark.parametrize` is used instead. Based on #20.
=> Remove parameterized

test/utils/amaranth_ext/test_coding.py, transactron/utils/amaranth_ext/coding.py
Fixes a problem introduced by #29, and adds tests which were originally in Amaranth.
=> Fix priority encoder after #29

test/lib/test_allocators.py, transactron/lib/allocators.py
This PR introduces an allocator which preserves allocation order information in the form of identifier permutation. The implementation performs deallocation by rotating some continuous range in the permutation.
=> Order preserving allocator

docs/transactions.md, test/core/test_transactions.py, test/lib/test_connectors.py, test/lib/test_reqres.py, test/lib/test_simultaneous.py, test/lib/test_transformers.py, test/test_methods.py, test/test_simultaneous.py, test/testing/test_validate_arguments.py, transactron/core/__init__.py, transactron/core/body.py, transactron/core/manager.py, transactron/core/method.py, transactron/core/schedulers.py, transactron/core/sugar.py, transactron/core/transaction.py, transactron/core/transaction_base.py, transactron/graph.py, transactron/lib/adapters.py, transactron/lib/fifo.py, transactron/lib/reqres.py, transactron/lib/simultaneous.py, transactron/lib/transformers.py, transactron/testing/profiler.py, transactron/utils/gen.py, transactron/utils/transactron_helpers.py
This PR introduces the following changes:
* Both `Transaction` and `Method` have an internal implementation of type `Body`.
* Multiple `Method` objects can refer to the same `Body`. This is used in the new implementation of `proxy`.
* Transaction to method transformation in simultaneous transactions now reuses the internal `Body` - no magic needed.
* Several implementation-related parameters moved from `Method.__init__` to `Method.body`. This makes `proxy` less weird - the proxy will always be like the target method.
* Also, the parameters are now stored using a `TypedDict`. This allowed to take care of some repetitive code.
* As a consequence, modules which require a method from the environment can declare them in the attributes, and then receive implementations via `proxy`.
TODO:
=> Transactron redesign: better proxying and cleaner implementation

transactron/testing/infrastructure.py
Currently timeouts only report failing on testbench finish but don't stop the simulation itself, which is not very helpful.
This PR fixes that by moving assert directly to timeout process.
=> Fix testbench timeouts to stop simulation

test/testing/test_method_mock.py, transactron/core/method.py, transactron/lib/adapters.py, transactron/testing/infrastructure.py, transactron/testing/method_mock.py
This PR changes `SimpleTestCircuit` so that `Adapter`s and `TestbenchIO`s can be automatically constructed for required methods. Type annotations is used to distinguish required methods from provided ones. Based on #30.
=> Improved SimpleTestCircuit

pyproject.toml, test/lib/test_storage.py, transactron/lib/metrics.py, transactron/lib/storage.py
* Previously memory element layout was `LayoutList` that was latter flattened to unsigned shape. Now memory accepts `ShapeLike` shape that is forwarded to memory
* granularity support was accidentally removed, fixed that (supported only `unsigned` and `ArrayLayout` shapes asserted by amaranth)
* renamed `elem_count` to `depth` for consistency with Amaranth
=> Adapt transactron.lib.storage to amaranth.lib.data

test/utils/amaranth_ext/test_elaboratables.py, transactron/lib/connectors.py, transactron/utils/amaranth_ext/elaboratables.py
This PR moves `StableSelectingNetwork` out of `lib`, as it's just an `Elaboratable` without any dependencies on the Transactron core. Also, the interface is changed to avoid using lists of signals, which are less ergonomic compared to `ArrayLayout`. Similar interface change is made in `MultiPriorityEncoder`.
=> Move StableSelectingNetwork out of lib

pyproject.toml, test/utils/test_component_interface.py, transactron/utils/amaranth_ext/component_interface.py
Redesign of concept from Coreblocks PR https://github.com/kuznia-rdzeni/coreblocks/pull/726.
Class that can be used both for typing and to get amaranth Signature for use in Component constructor.
=> `ComponentInterface` typing wrapper for lib.wiring interfaces

pyproject.toml, test/testing/test_method_mock.py, transactron/testing/infrastructure.py
To avoid repeating yourself, when subclassing is used, annotations from base classes are still used in `SimpleTestCircuit` to direct adapter creation.
Also, the use of `__annotations__` is replaced by `inspect.get_annotations`, which is described as a best practice in Python docs.
=> Look for Required/Provided annotations in base classes too

test/lib/test_simultaneous.py, transactron/core/manager.py, transactron/core/transaction_base.py
It turns out that, due to how simultaneous transactions are implemented, a transaction nested in and simultaneous with a method is run if the method has no callers. This PR detects such situations and disables the transaction. Maybe a little hacky, but it's the simplest solution I came up with.
Fixes #45.
=> Orphaned simultaneous transactions fix

transactron/utils/amaranth_ext/elaboratables.py, transactron/utils/amaranth_ext/memory.py
This PR adds a `OneHotMux` module, which is internally implemented using `OneHotSwitch`. This allows some cases where a one-hot mux is needed to be expressed cleaner.
Side note: it needs to be checked of `OneHotSwitch` actually reliably generates Yosys `$pmux` cells, as a lot has happened in Amaranth since this was last checked. I can't find any mention of reliable one-hot muxes in Amaranth codebase, so we should probably ask Amaranth devs about it.
=> One-hot mux circuit

transactron/utils/amaranth_ext/memory.py
This PR fixes a combinational loop present in recently merged #39. The issue prevents synthesis.
=> Fix combinational loop in multiport memory impls

test/lib/test_transformers.py, transactron/lib/transformers.py
This PR adds a method transformer which wraps a method with a nonexclusive method. This seems weird, but if we know that for some external reason the method will never be called more than once in the same clock cycle, doing this can reduce the complexity of the conflict graph.
=> Nonexclusive wrapper

pyproject.toml, test/core/test_transactions.py, transactron/core/manager.py
Currently, transactions which do not have priority relations have arbitrary scheduling order. This PR changes it so that the transactions with less conflicts are scheduled first. This should lead to granting transactions more greedily, which has the potential to improve performance. In practice, in current Coreblocks, some IPC numbers are improved, and some get slightly smaller. But still, I think having more determinism in the transaction scheduler is a good thing, as this will reduce weird performance changes on seemingly unrelated refactors, for example.
A new dependency is added, but given that Transactron relies heavily on graphs, `networkx` seems like a dependency that might be useful in the future (for example, for #13).
=> Conflict degree sort after priority topological sort

transactron/utils/data_repr.py
Recent change to `make_hashable` (#57) made things worse because of the good old "string is iterable but elements are one-character strings" problem. The old version failed silently (returned a generator with potentially unreliable hashes) on strings, the one in #57 causes a stack overflow. The version in this PR should work correctly for strings and also raises an exception in troublesome cases.
=> Fix make_hashable

test/utils/test_component_interface.py, transactron/core/body.py, transactron/core/manager.py
This PR fixes three issues:
* Conditional method calls could lead to invalid input values when custom combiners are used.
* Custom combiners could not get called if a method has only one caller, possibly leading to incorrect inputs.
* Test for `ComponentInterface` generated a warning.
Edit: It should be checked if this causes a performance regression. If so, the PR should be changed so that the common case (calls to "normal" blocking methods) is not penalized.
=> Fixes to combiners, fixed warning

test/lib/test_metrics.py, transactron/core/manager.py, transactron/core/method.py, transactron/core/transaction.py, transactron/lib/adapters.py, transactron/lib/metrics.py, transactron/lib/storage.py, transactron/testing/infrastructure.py, transactron/utils/_typing.py, transactron/utils/amaranth_ext/functions.py, transactron/utils/debug_signals.py
This PR modifies metrics to enable superscalar use - changing a metric multiple times in a single clock cycle. This is needed to be able to create superscalar circuits which utilize metrics.
The PR introduces a small syntactic change to method calls: the `enable` signal is renamed to `enable_call` and can be used as a keyword argument. This means that `enable_call` is now a reserved argument name. This was done to be able to remove method wrapper functions from metrics modules, which utilized an optional `cond` argument - which is basically `enable`. I'm not extra happy with the solution, but it gets the job done.
TODO:
=> Superscalar metrics

.github/workflows/publish-to-pypi.yml, pyproject.toml
This PR fixes publishing to TestPyPI by changing the way `setuptools_scm` generates version numbers. The `amaranth-stubs` dependency is changed to a PyPI published version to allow deployment to PyPI and TestPyPI.
=> Testpypi fix

transactron/lib/fifo.py
This PR makes the `write_width` parameter, which is documented as optional, actually optional.
=> Optional write width in WideFifo

test/lib/test_reqres.py, transactron/lib/reqres.py
The use of `exact_log2` in `Serializer` introduces an unnecessary and undocumented power-of-2 requirement on the port count. This PR fixes that.
=> Allow Serializer to have non-power-of-2 number of ports

test/test_simultaneous.py, transactron/core/manager.py, transactron/core/method.py, transactron/lib/reqres.py, transactron/lib/transformers.py
This PR removes the need to supply a `TModule` argument to `Method.proxy`. The `ready`, `run` etc. signals are now set from the `TransactionManager`. This will make future API changes simpler. Also, a bug when `proxy` might be called inside `m.If` is fixed.
=> Remove module argument from Method.proxy

test/lib/test_fifo.py, transactron/lib/fifo.py
This PR makes slight refactor changes to the `BasicFifo` module:
* Docstrings are changed to per-method style, the outdated info about `clear` priority is removed.
* Signals which were declared using `bit_length` now use `range` instead, which I believe to be more idiomatic.
* The `read_ready` and `write_ready` signals are no longer exposed. There is no need to - these are the same as `read.ready` and `write.ready`.
* `read_methods` and `write_methods` are removed. After introducing `Methods`, there is no need for compatibility interfaces like this.
* `width` attribute is removed, `layout` is enough.
* Internal memory now uses `layout` as element shape.
* Test uses `SimpleTestCircuit`, tests the `peek` method, and the `clear` method is called from a separate process.
=> FIFO refactor

transactron/lib/transformers.py
`CatTrans` was a simple toy example of a Transactron component with a transaction, calling external methods. Was never really used outside of early proof-of-concept, but somehow found itself in the library. `MethodProduct` is more general. This PR removes it.
=> Remove CatTrans

test/core/test_transactions.py, test/test_branches.py, test/test_methods.py, transactron/core/__init__.py, transactron/core/context.py, transactron/core/manager.py, transactron/testing/infrastructure.py
This PR factors out the Transactron context wrappers to a separate file and gives them hopefully less ambiguous names.
=> Refactor Transactron context wrappers

docs/transactions.md, test/core/test_transactions.py, test/test_methods.py, test/test_simultaneous.py, transactron/core/method.py, transactron/core/transaction.py, transactron/lib/adapters.py, transactron/lib/simultaneous.py, transactron/profiler.py, transactron/testing/profiler.py, transactron/utils/gen.py
I believe that having distinct names for handshake signals for transactions (`request`/`grant`) and methods (`ready`/run`) is confusing and unneeded:
1. Many docstrings already in the code actually explain the transaction signals using method terminology.
2. In the current implementation, these signals are actually the same under the hood - both transactions and methods are implemented in terms of bodies, and sometimes a transaction body can actually become a method body (simultaneous transactions).
3. Transactions are in practice implemented rarely than methods (in Coreblocks, 60 transactions vs 150 methods), so it's easy to forget the names used in transactions.
Therefore I believe that it's time to change the user-facing names.
=> Rename request/grant to ready/run

test/test_simultaneous.py, transactron/core/method.py, transactron/lib/adapters.py, transactron/lib/connectors.py, transactron/lib/reqres.py, transactron/lib/transformers.py
As discussed in #79, `proxy` is now intended to be a mechanism for providing method implementations to components which call external methods. With its new important function, it's time to give it a more descriptive name.
=> Rename proxy to provide

test/core/test_transactions.py, transactron/core/keys.py, transactron/core/manager.py, transactron/core/method.py, transactron/core/transaction.py
Transactions and methods are collected using `ListKeys` instead of using `TransactionManager` attributes. In consequence, transactions can now be declared outside `elaborate`.
=> Collect transactions and methods using keys

transactron/core/manager.py, transactron/core/method.py
There is a performance issue in Amaranth's pysim which causes slowdowns dependent on the module in which the signal is assigned. This PR is intended to work around the issue. It should still be fixed in Amaranth IMHO - because of how Transactron is constructed, a fix will probably speed up Coreblocks tests quite a lot.
=> Pysim performance workaround
